[package]
name = "ss15"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.0"
bevy_renet = { git = "https://github.com/lucaspoffo/renet", package = "bevy_renet" }
bincode = "1.3"
rand = "0.9.1"
serde = "1.0.219"

[profile.dev.package."*"]
opt-level = 3
