[package]
name = "ss15"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy_renet = "1.0.0"
bincode = "1.3.3"
rand = "0.9.0"
serde = "1.0.219"

[profile.dev.package."*"]
opt-level = 3
